name: Deploy

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: "https://halivert.dev/progressive-overload/"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/setup-node@v2
        with:
          node-version: "16.3"
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: Build JS files
        run: |
          cd frontend
          yarn
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: frontend/build
